# '/메뉴' 를 입력했을 때 기본적으로 나올 메뉴
default-menu: "예시"

menu:
  예시:
    title: "워프"
    size: 54

    # font 파일
    font: ""
    # negative space font를 사용할 때 쓸 수 있는 옵션
    backspaces: 0

    button:
      야생:
        slots: "0, 1, 2"
        material: GRASS_BLOCK
        # 이름과 로어에 papi 지원합니다.
        display-name: "&f야생 워프창"
        lore: []
        custom-model-data: 0

        # 소리
        sound:
          name: "minecraft:ui.button.click"
          volume: 1
          pitch: 1

        # 클릭 시 화면을 닫을건지
        close-inventory-if-clicked: true

        # 유저 권한 또는 콘솔 권한으로 명령어를 실행할 수 있습니다.
        # 콘솔 권한 ex) "CONSOLE:메뉴관리 열기 예시2 %player%"
        # 유저 권한 ex) "PLAYER:스텟"
        # %player% = 유저
        commands:
          - "CONSOLE:메뉴관리 열기 예시2 %player%"